#!/bin/bash
#
# Debian startup script for the Centrify DirectControl infrastructure.
#
# description: Centrify DirectControl interface support
# processname: adclient
# pidfile: /var/run/adclient.pid
# config: /etc/centrifydc/centrifydc.conf

# Configurable environment variables:
#   DAEMON  Alternate daemon location and name
#   ADINFO    Alternate location for adinfo command
#   OPTIONS   Daemon command line options. These are combined with any
#             additional command line parameters.

### BEGIN INIT INFO
# Provides:          adclient
# Required-Start:    $local_fs
# Should-Start:      $syslog $network
# Required-Stop:     $local_fs
# Should-Stop:       $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CentrifyDC adclient daemon for AD services
# Description:       Start centrifydc to allow Active Directory
### END INIT INFO

# Source CDC function library.
test -f /etc/centrifydc/scripts/functions.cdc || exit 0
. /etc/centrifydc/scripts/functions.cdc

test -f "$DAEMON" || exit 0

# Execute command

CMD=$1
[ $# -gt 0 ] && shift
OPTIONS="$OPTIONS $@"

# Use Upstart to run CMD if needed
run_with_upstart $CMD && exit $UPSTART_EXITCODE

case "$CMD" in
    start)
        program_check_root $CMD
        program_check
        echo -n "Starting $NAME: "
        start-stop-daemon --start --quiet --exec $DAEMON --pidfile $PIDFILE \
            -- $OPTIONS
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
             echo "OK"
             wait_adclient
        else
             echo "FAILED"
        fi
        exit $RETVAL
        ;;
        
    stop)
        program_check_root $CMD
        echo -n "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
            --retry TERM/1/1/1/1/1/KILL
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            # Had to kill daemon. PID file wasn't cleaned up.
            rm -f $PIDFILE
        fi
        [ $RETVAL -eq 0 ] && echo "OK" || echo "FAILED"
        exit $RETVAL
        ;;
        
    status)
        program_status
        if [ -n "$PID" ]; then
            exit 0
        else
            exit 1
        fi
        ;;
        
    restart)
        program_check_root $CMD
        $0 stop
        $0 start $OPTIONS
        ;;
        
    condrestart)
        program_check_root $CMD
        $0 status >/dev/null && $0 restart $OPTIONS
        ;;
        
    reload|force-reload)
        program_check_root $CMD
        echo -n "Reloading $NAME "
        $0 status >/dev/null && /usr/sbin/adreload
        RETVAL=$?
        echo "."
        exit $RETVAL
        ;;
                
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload}"
        exit 1
esac
